theme: jekyll-theme-architect
title: Welcome to Olivier-504's homepage!
description: This page will be incrementally updated with varying project types.

For this Eportfolio I am sharing three projects that fit under categories of the following:

1: Software Engineering and Design
2: Algorithms and Data Structures 
3: Databases

Each of the projects demonstrate 
